blank_issues_enabled: true
contact_links:
  - name: Feature Requests & Questions
    url: https://github.com/rhinobase/hono-rate-limiter/discussions
    about: Please ask and answer questions here.
  - name: Community Chat
    url: https://discord.gg/4rNs6ywvtV
    about: A dedicated discord server hosted by Rhinobase
